# Generated by Django 2.2.8 on 2019-12-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('edition', models.FloatField()),
                ('publication_year', models.IntegerField()),
                ('author', models.ManyToManyField(to='authors.Author')),
            ],
        ),
    ]
